version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exampleSuperSecretPassword
    volumes:
      - mongodb_data:/data/db1

volumes:
  mongodb_data:
